services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: site_afiha
      POSTGRES_USER: master_afiha
      POSTGRES_PASSWORD: 54321
    ports:
      - '5430:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data: 