# Generated by Django 4.2.13 on 2024-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('url_img', models.TextField(blank=True)),
                ('time_creat', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
