# Generated by Django 4.2.13 on 2024-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiha', '0002_posts_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('url_img', models.TextField(blank=True)),
                ('time_creats', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time_creat']},
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['-time_creat'], name='afiha_posts_time_cr_c5586b_idx'),
        ),
    ]
