# Generated by Django 4.2.13 on 2024-06-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiha', '0003_news_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='posts',
            name='afiha_posts_time_cr_c5586b_idx',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='time_creat',
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afiha.posts'),
        ),
    ]
