# Generated by Django 4.2.13 on 2024-07-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiha', '0005_alter_event_options_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url_img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
