# Generated by Django 4.2.13 on 2024-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiha', '0006_alter_news_url_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_time'], 'verbose_name': 'Расписание представлений', 'verbose_name_plural': 'Расписание представлений'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='afiha_event_event_t_2c82ee_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_time'], name='afiha_event_event_t_3f2385_idx'),
        ),
    ]
